"""B9: source MAC never substitutes for exact issued/S16/S17 authority."""
from __future__ import annotations

import asyncio
import json
from dataclasses import replace

import pytest

from adapters.mineflayer.execution import (
    WorldConsequenceStatus,
    build_mineflayer_command,
    execute_mineflayer_command,
)
from experiments.ac_b_b9_signed_s16 import (
    ExternalS16EvidenceGate,
    OfflineS16SourceIssuer,
    TrustedWorldEpoch,
    UnqualifiedWorldEvidence,
    new_fixture_keys,
    parse_signed_evidence,
    serialize_signed_evidence,
)
from relay_self.action import ActionState
from relay_self.action_feedback import (
    LearningFeedbackInterpretationStatus,
    interpret_action_outcome_as_learning_feedback,
)
from relay_self.action_outcome import (
    ActionOutcomeDisposition,
    record_interpreted_action_outcome,
)
from relay_self.learning import (
    MissingLearningAuthority,
    commit_learning_update,
    propose_learning_update,
)
from relay_self.provenance import Provenance

from test_action_feedback_qualification import (
    feedback_criterion,
    issued_chain,
    learning_rule,
    learning_state,
    successful_session,
)


def provenance(name: str) -> Provenance:
    return Provenance("b9-offline-test", name)


def qualified_fixture():
    chain = issued_chain()
    issued = chain[-1]
    supervisor = chain[-2]
    binding = chain[-4]
    assert issued.state is ActionState.ISSUED
    command = build_mineflayer_command(issued, binding)
    consequence = asyncio.run(execute_mineflayer_command(
        successful_session(command), command,
        provenance=provenance("known-fake-world-consequence"),
    ))
    assert consequence.status is WorldConsequenceStatus.EXECUTED
    key = new_fixture_keys()
    issuer = OfflineS16SourceIssuer(key, consequence.session_id)
    epoch = TrustedWorldEpoch(consequence.session_id, 0)
    gate = ExternalS16EvidenceGate(key, epoch)
    signed = issuer.sign(consequence)
    return issued, supervisor, binding, consequence, issuer, gate, signed, key


def test_source_bound_full_s16_consequence_is_pure_read_only_interpretation():
    issued, supervisor, binding, consequence, issuer, gate, receipt, _ = (
        qualified_fixture()
    )
    assert consequence.before_observation is not None
    assert consequence.dispatch_receipt is not None
    assert consequence.cleanup_receipt is not None
    assert consequence.after_observation is not None
    assert consequence.movement_distance > 0
    assert issuer.session == consequence.session_id
    assert receipt.consequence_digest
    reloaded = parse_signed_evidence(serialize_signed_evidence(receipt))
    assert reloaded == receipt and reloaded is not receipt
    original = supervisor.get(issued.action_id)
    result = gate.qualify(issued, binding, consequence, reloaded)
    assert result.disposition is ActionOutcomeDisposition.OUTCOME
    assert result.reason_code == "observed_execution"
    assert result.source_status == WorldConsequenceStatus.EXECUTED.value
    assert result.provenance.reference == receipt.event_id
    assert result.world_provenance == consequence.provenance
    assert result.action_id == issued.action_id
    assert result.binding_id == binding.binding_id
    assert supervisor.get(issued.action_id) is original
    assert original.state is ActionState.ISSUED


def test_explicit_supervisor_outcome_and_s17_criterion_needed_for_feedback():
    issued, supervisor, binding, consequence, _, gate, receipt, _ = (
        qualified_fixture()
    )
    interpreted = gate.qualify(issued, binding, consequence, receipt)
    assert supervisor.get(issued.action_id).state is ActionState.ISSUED
    closed = record_interpreted_action_outcome(
        supervisor, interpreted, at_ns=20,
    )
    assert closed.state is ActionState.OUTCOME
    no_criterion = None
    assert no_criterion is None  # no implicit criterion generated by gate
    real = interpret_action_outcome_as_learning_feedback(
        closed, interpreted, feedback_criterion(),
        provenance=provenance("only-explicit-criterion"),
    )
    assert real.status is LearningFeedbackInterpretationStatus.PRODUCED
    assert real.feedback is not None
    assert real.feedback.consequence_ref == real.outcome_ref
    assert real.world_provenance == interpreted.world_provenance
    mismatched = interpret_action_outcome_as_learning_feedback(
        closed, interpreted, feedback_criterion(reason="wrong_reason"),
        provenance=provenance("mismatched-criterion"),
    )
    assert mismatched.status is LearningFeedbackInterpretationStatus.NOT_APPLICABLE
    assert mismatched.feedback is None
    state = learning_state()
    proposal = propose_learning_update(state, real.feedback, learning_rule())
    assert proposal.proposed_value == 4 and state.value == 3
    with pytest.raises(MissingLearningAuthority):
        commit_learning_update(
            state, proposal, None,
            provenance=provenance("no-s10-commit-authority"),
        )
    assert state.value == 3 and state.revision == 0


def test_generic_b7_cue_action_success_is_not_s16_world_consequence():
    issued, supervisor, binding, consequence, _, gate, receipt, _ = (
        qualified_fixture()
    )
    generic = {
        "event_id": "b7-world:event:1", "session": consequence.session_id,
        "revision": 0, "a": 0, "b": 1, "action": 0,
        "success": True, "kind": "OBSERVED_ACTION",
    }
    with pytest.raises(UnqualifiedWorldEvidence, match="generic receipt"):
        gate.qualify(issued, binding, generic, receipt)
    with pytest.raises(UnqualifiedWorldEvidence, match="B7 generic"):
        gate.qualify(issued, binding, consequence, generic)
    assert supervisor.get(issued.action_id).state is ActionState.ISSUED


def test_wrong_signer_key_and_tampered_mac_digest_fail_closed():
    issued, supervisor, binding, consequence, _, gate, receipt, key = (
        qualified_fixture()
    )
    foreign = ExternalS16EvidenceGate(new_fixture_keys(), gate.live_epoch)
    with pytest.raises(UnqualifiedWorldEvidence, match="MAC"):
        foreign.qualify(issued, binding, consequence, receipt)
    for changed in (
        replace(receipt, mac="0" * 64),
        replace(receipt, consequence_digest="0" * 64),
        replace(receipt, action_id="other_action"),
        replace(receipt, binding_id="other_binding"),
        replace(receipt, action_ref="WAIT"),
        replace(receipt, world_reference="forged"),
        replace(receipt, source_status="failed"),
    ):
        with pytest.raises(UnqualifiedWorldEvidence):
            gate.qualify(issued, binding, consequence, changed)
    assert key != new_fixture_keys()
    assert supervisor.get(issued.action_id).state is ActionState.ISSUED


def test_signed_world_full_contents_immutable_against_modification():
    issued, supervisor, binding, consequence, _, gate, receipt, _ = (
        qualified_fixture()
    )
    variants = (
        replace(consequence, movement_distance=consequence.movement_distance + .1),
        replace(consequence, provenance=provenance("altered-source-reference")),
        replace(
            consequence,
            before_observation=replace(
                consequence.before_observation, session_id="foreign-session"
            ),
        ),
        replace(
            consequence,
            dispatch_receipt=replace(
                consequence.dispatch_receipt, action_id="other-action"
            ),
        ),
        replace(
            consequence,
            cleanup_receipt=replace(
                consequence.cleanup_receipt, action_id="other-cleanup"
            ),
        ),
        replace(
            consequence,
            after_observation=replace(
                consequence.after_observation, session_id="foreign-session"
            ),
        ),
    )
    for altered in variants:
        with pytest.raises(UnqualifiedWorldEvidence, match="digest"):
            gate.qualify(issued, binding, altered, receipt)
    assert supervisor.get(issued.action_id).state is ActionState.ISSUED


def test_epoch_revision_change_and_session_collision_block_replay():
    issued, supervisor, binding, consequence, _, gate, receipt, key = (
        qualified_fixture()
    )
    wrong_session = ExternalS16EvidenceGate(
        key, TrustedWorldEpoch("other-session", 0),
    )
    with pytest.raises(UnqualifiedWorldEvidence, match="epoch"):
        wrong_session.qualify(issued, binding, consequence, receipt)
    gate.live_epoch.advance()
    with pytest.raises(UnqualifiedWorldEvidence, match="epoch"):
        gate.qualify(issued, binding, consequence, receipt)
    assert supervisor.get(issued.action_id).state is ActionState.ISSUED


def test_duplicate_signed_event_id_cannot_be_spent_twice():
    issued, _, binding, consequence, _, gate, receipt, _ = qualified_fixture()
    gate.qualify(issued, binding, consequence, receipt)
    with pytest.raises(UnqualifiedWorldEvidence, match="already consumed"):
        gate.qualify(issued, binding, consequence, receipt)


def test_json_exact_fields_duplicate_keys_and_bool_int_confusion():
    issued, _, binding, consequence, _, gate, receipt, _ = qualified_fixture()
    raw = serialize_signed_evidence(receipt)
    value = json.loads(raw)
    bad = (
        raw.replace('"event_id":', '"event_id":"fake","event_id":', 1),
        json.dumps({**value, "unknown": "value"}),
        json.dumps({k: v for k, v in value.items() if k != "mac"}),
    )
    for item in bad:
        with pytest.raises(UnqualifiedWorldEvidence):
            parse_signed_evidence(item)
    invalid_revision = replace(receipt, revision=True)
    with pytest.raises(UnqualifiedWorldEvidence, match="invalid revision"):
        gate.qualify(issued, binding, consequence, invalid_revision)
    invalid_sequence = replace(receipt, sequence=True)
    with pytest.raises(UnqualifiedWorldEvidence, match="invalid sequence"):
        gate.qualify(issued, binding, consequence, invalid_sequence)


def test_no_self_issued_authority_from_any_signed_evidence():
    issued, supervisor, binding, consequence, _, gate, receipt, _ = (
        qualified_fixture()
    )
    # An S16 interpretation never changes an owner, even with a valid MAC.
    interpreted = gate.qualify(issued, binding, consequence, receipt)
    assert interpreted.disposition is ActionOutcomeDisposition.OUTCOME
    assert supervisor.open_actions != ()
    assert supervisor.get(issued.action_id).state is ActionState.ISSUED


def test_externally_signed_failure_and_unavailable_not_converted_to_success():
    issued, supervisor, binding, consequence, issuer, _, _, key = (
        qualified_fixture()
    )
    failed = replace(
        consequence,
        status=WorldConsequenceStatus.FAILED,
        error="test-fixture-adapter-error",
    )
    undetermined = replace(
        consequence, status=WorldConsequenceStatus.UNDETERMINED,
    )
    gate = ExternalS16EvidenceGate(
        key, TrustedWorldEpoch(consequence.session_id, 0),
    )
    fail_interpretation = gate.qualify(
        issued, binding, failed, issuer.sign(failed),
    )
    unavailable_interpretation = gate.qualify(
        issued, binding, undetermined, issuer.sign(undetermined),
    )
    assert fail_interpretation.disposition is ActionOutcomeDisposition.UNKNOWN
    assert unavailable_interpretation.disposition is (
        ActionOutcomeDisposition.UNAVAILABLE
    )
    assert supervisor.get(issued.action_id).state is ActionState.ISSUED
